name: update_docs
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
jobs:
  publish:
    name: Publish to retype branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: retypeapp/action-build@latest
        with:
          config: docs

      - uses: retypeapp/action-github-pages@latest
        with:
          branch: retype
          update-branch: true
